"""initial_schema_with_indexes

Revision ID: e47466715ca1
Revises: 
Create Date: 2026-03-15 12:20:51.941795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e47466715ca1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_answer_keys_test_id'), 'answer_keys', ['test_id'], unique=False)
    op.create_index(op.f('ix_class_groups_owner_id'), 'class_groups', ['owner_id'], unique=False)
    op.create_index(op.f('ix_class_groups_school_id'), 'class_groups', ['school_id'], unique=False)
    op.create_index(op.f('ix_question_flags_question_id'), 'question_flags', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_flags_teacher_id'), 'question_flags', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_questions_created_by'), 'questions', ['created_by'], unique=False)
    op.create_index(op.f('ix_questions_school_id'), 'questions', ['school_id'], unique=False)
    op.create_index(op.f('ix_questions_subject_id'), 'questions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_questions_topic_id'), 'questions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_scan_batches_class_id'), 'scan_batches', ['class_id'], unique=False)
    op.create_index(op.f('ix_scan_batches_test_id'), 'scan_batches', ['test_id'], unique=False)
    op.create_index(op.f('ix_scan_results_scan_batch_id'), 'scan_results', ['scan_batch_id'], unique=False)
    op.create_index(op.f('ix_scan_results_student_id'), 'scan_results', ['student_id'], unique=False)
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_school_id'), 'subjects', ['school_id'], unique=False)
    op.create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    op.create_index(op.f('ix_test_assignments_assigned_by'), 'test_assignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_test_assignments_class_id'), 'test_assignments', ['class_id'], unique=False)
    op.create_index(op.f('ix_test_assignments_school_id'), 'test_assignments', ['school_id'], unique=False)
    op.create_index(op.f('ix_test_assignments_teacher_id'), 'test_assignments', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_test_assignments_test_id'), 'test_assignments', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_questions_question_id'), 'test_questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_test_questions_test_id'), 'test_questions', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_sections_test_id'), 'test_sections', ['test_id'], unique=False)
    op.create_index(op.f('ix_tests_subject_id'), 'tests', ['subject_id'], unique=False)
    op.create_index(op.f('ix_tests_teacher_id'), 'tests', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_topics_subject_id'), 'topics', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_subject_id'), table_name='topics')
    op.drop_index(op.f('ix_tests_teacher_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_subject_id'), table_name='tests')
    op.drop_index(op.f('ix_test_sections_test_id'), table_name='test_sections')
    op.drop_index(op.f('ix_test_questions_test_id'), table_name='test_questions')
    op.drop_index(op.f('ix_test_questions_question_id'), table_name='test_questions')
    op.drop_index(op.f('ix_test_assignments_test_id'), table_name='test_assignments')
    op.drop_index(op.f('ix_test_assignments_teacher_id'), table_name='test_assignments')
    op.drop_index(op.f('ix_test_assignments_school_id'), table_name='test_assignments')
    op.drop_index(op.f('ix_test_assignments_class_id'), table_name='test_assignments')
    op.drop_index(op.f('ix_test_assignments_assigned_by'), table_name='test_assignments')
    op.drop_index(op.f('ix_teachers_school_id'), table_name='teachers')
    op.drop_index(op.f('ix_subjects_school_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.drop_index(op.f('ix_scan_results_student_id'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_scan_batch_id'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_batches_test_id'), table_name='scan_batches')
    op.drop_index(op.f('ix_scan_batches_class_id'), table_name='scan_batches')
    op.drop_index(op.f('ix_questions_topic_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_subject_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_school_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_by'), table_name='questions')
    op.drop_index(op.f('ix_question_flags_teacher_id'), table_name='question_flags')
    op.drop_index(op.f('ix_question_flags_question_id'), table_name='question_flags')
    op.drop_index(op.f('ix_class_groups_school_id'), table_name='class_groups')
    op.drop_index(op.f('ix_class_groups_owner_id'), table_name='class_groups')
    op.drop_index(op.f('ix_answer_keys_test_id'), table_name='answer_keys')
    # ### end Alembic commands ###
